.github/workflows/pr.yaml, .github/workflows/release.yaml, README.md, charts/dscp-ipfs/Chart.lock, charts/dscp-ipfs/Chart.yaml, charts/dscp-ipfs/ci/ct-values.yaml, charts/dscp-ipfs/templates/_helpers.tpl, charts/dscp-ipfs/templates/configmap.yaml, charts/dscp-ipfs/templates/secret.yaml, charts/dscp-ipfs/templates/service.yaml, charts/dscp-ipfs/templates/statefulset.yaml, charts/dscp-ipfs/values.yaml, charts/dscp-node/Chart.yaml, charts/dscp-node/ci/ct-values.yaml
=> Added dscp-ipfs

charts/dscp-api/Chart.lock, charts/dscp-api/Chart.yaml, charts/dscp-api/ci/ct-values.yaml, charts/dscp-api/templates/_helpers.tpl, charts/dscp-api/templates/configmap.yaml, charts/dscp-api/templates/deployment.yaml, charts/dscp-api/templates/ingress.yaml, charts/dscp-api/templates/secret.yaml, charts/dscp-api/templates/service.yaml, charts/dscp-api/values.yaml
=> Added dscp-api

charts/dscp-ipfs/Chart.lock, charts/dscp-ipfs/Chart.yaml, charts/dscp-ipfs/templates/configmap.yaml, charts/dscp-ipfs/templates/statefulset.yaml, charts/dscp-ipfs/values.yaml
Fixing a bug with missing values and missing envars.
=> Fixing bug in previous helm chart

README.md, charts/wasp-routing-service/Chart.lock, charts/wasp-routing-service/Chart.yaml, charts/wasp-routing-service/ci/ct-values.yaml, charts/wasp-routing-service/templates/_helpers.tpl, charts/wasp-routing-service/templates/configmap.yaml, charts/wasp-routing-service/templates/deployment.yaml, charts/wasp-routing-service/values.yaml
Adds the `wasp-routing-service`
=> Added and upgraded wasp-routing-service chart

README.md, charts/wasp-ws-event-service/Chart.lock, charts/wasp-ws-event-service/Chart.yaml, charts/wasp-ws-event-service/ci/ct-values.yaml, charts/wasp-ws-event-service/templates/_helpers.tpl, charts/wasp-ws-event-service/templates/configmap.yaml, charts/wasp-ws-event-service/templates/deployment.yaml, charts/wasp-ws-event-service/templates/ingress.yaml, charts/wasp-ws-event-service/templates/secret.yaml, charts/wasp-ws-event-service/templates/service.yaml, charts/wasp-ws-event-service/values.yaml, charts/wasp-ws-reading-service/Chart.lock, charts/wasp-ws-reading-service/Chart.yaml, charts/wasp-ws-reading-service/ci/ct-values.yaml, charts/wasp-ws-reading-service/templates/_helpers.tpl, charts/wasp-ws-reading-service/templates/configmap.yaml, charts/wasp-ws-reading-service/templates/deployment.yaml, charts/wasp-ws-reading-service/templates/ingress.yaml, charts/wasp-ws-reading-service/templates/secret.yaml, charts/wasp-ws-reading-service/templates/service.yaml, charts/wasp-ws-reading-service/values.yaml
Adds the two websocket services
=> Adds websocket services

charts/dscp-api/Chart.yaml, charts/dscp-api/templates/ingress.yaml, charts/dscp-api/values.yaml, charts/dscp-identity-service/Chart.yaml, charts/dscp-identity-service/templates/ingress.yaml, charts/dscp-identity-service/values.yaml, charts/dscp-ipfs/Chart.yaml, charts/dscp-ipfs/values.yaml, charts/dscp-node/Chart.yaml, charts/dscp-node/values.yaml, renovate.json
Also attempts to configure renovateBot to automatically increment things
=> Bump versions and add ingress hosts

charts/dscp-api/Chart.lock, charts/dscp-api/Chart.yaml, charts/dscp-api/values.yaml, charts/dscp-identity-service/Chart.yaml, charts/dscp-identity-service/values.yaml
Bumps image versions to support `auth.type: EXTERNAL`
=> Bumping to image versions that support auth.type: EXTERNAL

charts/dscp-api/Chart.lock, charts/dscp-api/Chart.yaml, charts/dscp-api/ci/ct-values.yaml, charts/dscp-api/templates/_helpers.tpl, charts/dscp-api/templates/configmap.yaml, charts/dscp-api/values.yaml, charts/dscp-identity-service/Chart.lock, charts/dscp-identity-service/Chart.yaml, charts/dscp-identity-service/values.yaml
Bumps dscp-api and dscp-identity-service to take advantage of new auth.type features.
=> Bumping versions

charts/sqnc-identity-service/Chart.lock, charts/sqnc-identity-service/Chart.yaml, charts/sqnc-identity-service/ci/ct-values.yaml, charts/sqnc-ipfs/Chart.lock, charts/sqnc-ipfs/Chart.yaml, charts/sqnc-ipfs/ci/ct-values.yaml, charts/sqnc-matchmaker-api/Chart.lock, charts/sqnc-matchmaker-api/Chart.yaml, charts/sqnc-matchmaker-api/ci/ct-values.yaml
Upgrades all `sqnc` charts dependencies
=> Upgrade sqnc dependencies

charts/veritable-cloudagent/Chart.yaml, charts/veritable-cloudagent/templates/ingress.yaml
N/A
This PR fixes the backend service that the ingress resources should be pointing at.
Previously we were pointing to the communication endpoints service (Either http(s) or WS).  This updates the chart so that instead we point to the admin API for the specified ingress resources.
N/A
N/A
N/A
=> Fixing bug with ingress resources

charts/veritable-ui/Chart.yaml, charts/veritable-ui/README.md, charts/veritable-ui/templates/secret-session-cookie.yaml, charts/veritable-ui/values.yaml
Fixed a bug with how we present the cookie session key
Presents the secret as a comma separated string instead of a YAMLified array.
N/A
N/A
N/A
=> Cookie-session-key bug

.github/workflows/renovate.yaml, renovate.config.js
ENG-101
Config item for self hosted wasn't asserted properly
N/A
N/A
N/A
N/A
=> Fixing lack of config item to detect renovate

renovate.config.js, scripts/bump-chart-version.sh
Adds labels and makes use of the readme-generator to update the README when we change values in a chart
ENG-101
Adds consistent labeling and adds helm readme generator by Bitnami
N/A
N/A
N/A
N/A
=> readme-generator

.github/workflows/renovate.yaml
N/A
Schedules renovate runs
Schedules renovate runs every hour between 00:00 to 05:00 and then between 18:00 to 00:00
N/A
N/A
N/A
=> Scheduling renovate helm runs

.github/workflows/renovate.yaml
N/A
Disabled scheduled updates
Something is funky with one of the updates concerning postgresql 17 or the new bitnami postgres chart, disabling prior to investigation.
N/A
None of the potentially buggy charts are in production usage
N/A
=> Disabling scheduling and on updates to this renovate.yaml

charts/bridgeai-prediction-service/Chart.yaml, charts/bridgeai-prediction-service/values.yaml
BRID-111
Adds swagger paths
Adds swagger UI and api docs paths
N/A
N/A
N/A
=> Add Swagger Paths

charts/bridgeai-prediction-service/Chart.yaml, charts/bridgeai-prediction-service/README.md, charts/bridgeai-prediction-service/templates/deployment.yaml, charts/bridgeai-prediction-service/values.yaml
N/A
Adds DB envs to the deployment and updates ingress paths
Adds DB envs to the deployment as they were missing.
Fixes incorrect paths in the ingress
N/A
N/A
N/A
=> Prediction service - DB Envs

charts/sqnc-matchmaker-api/Chart.yaml, charts/sqnc-matchmaker-api/values.yaml
SQNC-136
Bump image tag to include bug fix
=> Bumping chart version to fix matchmaker health check

charts/sqnc-matchmaker-api/Chart.lock, charts/sqnc-matchmaker-api/Chart.yaml, charts/sqnc-matchmaker-api/ci/ct-values.yaml, charts/sqnc-matchmaker-api/templates/_helpers.tpl, charts/sqnc-matchmaker-api/values.yaml
SQNC-55
Fixes bug where external hosts weren't being evaluated
In #735 the template used to establish the host for identity and ipfs was changed but never includes anoverride if an external host is used. This fixes that
None
None
None
=> Fix issue with external hosts not overriding

charts/sqnc-matchmaker-api/Chart.lock, charts/sqnc-matchmaker-api/Chart.yaml, charts/sqnc-matchmaker-api/README.md, charts/sqnc-matchmaker-api/ci/ct-values.yaml, charts/sqnc-matchmaker-api/templates/_helpers.tpl, charts/sqnc-matchmaker-api/templates/deployment.yaml, charts/sqnc-matchmaker-api/templates/tests/test-availability.yaml, charts/sqnc-matchmaker-api/values.yaml
https://digicatapult.atlassian.net/browse/SQNC-126
Upgrades matchmaker to v5 integrating the attachment API
This change updates the matchmaker chart to support ve 5 of the application. This includes integration with the attachment API and swapping out a number of envs.
None
None
None
=> Upgrade matchmaker to v5

renovate.config.js
SQNC-157
We don't intend to upgrade the Bitnami PostgreSQL sub-chart due to breaking changes between each major version of PostgreSQL. Ignoring the dependency will ensure that Renovate skips any future updates to that sub-chart.
=> Add PostgreSQL to ignore list

charts/sqnc-matchmaker-api/Chart.yaml, charts/sqnc-matchmaker-api/values.yaml
SQNC-157
Removes the attachment path
Was causing a conflict in staging with ingress paths
=> Updates paths

charts/sqnc-matchmaker-api/Chart.yaml, charts/sqnc-matchmaker-api/values.yaml
https://digicatapult.atlassian.net/browse/SQNC-132
Bump matchmaker to 6.2.3
Bump to include bug fix from https://github.com/digicatapult/sqnc-matchmaker-api/pull/661
None
None
N/A
=> Update matchmaker version

renovate.config.js
=> update one dependency per PR per chart

renovate.config.js
=> renovate group name update

charts/veritable-ui/Chart.yaml, charts/veritable-ui/templates/deployment.yaml
There's an environment variable duplicated on all Veritable UI pods and it needs removing.
=> Remove duplicated variable

renovate.config.js
Adds automerge label
N/A
Adds the automerge label to charts that should automatically merge.
=> automerge label

.github/workflows/chart-sqnc-identity-service.yml, charts/sqnc-identity-service/Chart.yaml, charts/sqnc-identity-service/README.md, charts/sqnc-identity-service/values.yaml
VR-446
Replaces postgresql bitnami repository in our charts.
=> sqnc-identity-service - replace postgresql repositories

charts/veritable-cloudagent/Chart.yaml, charts/veritable-cloudagent/README.md, charts/veritable-cloudagent/values.yaml
VR-446
Uses bitnamilegacy repository
=> Updating cloudagent to use bitnamilegacy image repository

charts/veritable-ui/Chart.lock, charts/veritable-ui/Chart.yaml, charts/veritable-ui/README.md, charts/veritable-ui/values.yaml
VR-446
Updating veritable-ui to use bitnamilegacy image repository
=> Updating veritable-ui to use bitnamilegacy image repository

charts/sqnc-attachment-api/Chart.lock, charts/sqnc-attachment-api/Chart.yaml, charts/sqnc-attachment-api/README.md, charts/sqnc-attachment-api/values.yaml
SQNC-198
Updating attachment-api to use bitnamilegacy image repository
=> Updating attachment-api to use bitnamilegacy image repository

.github/workflows/chart-sqnc-identity-service.yml, .github/workflows/pr.yaml, .github/workflows/release.yaml
VR-471; SQNC-198
This PR is to include the CNPG operator's repository and install it prior to any testing, as it'll be a dependency for most of our charts.
=> Add CNPG operator as a prerequisite

.github/workflows/pr.yaml
A bug was introduced with #1584, whereby the logic for the CNPG operator becomes dependent on the wrong output. It should be `changed`, not `changed_named_charts`.
=> Fix operator step logic
